#!/bin/bash
# intcurl
# this script is designed to test the location of a 301 redirect on resources that are found behind an HTTPS authentication
# as well as on a certain staging enviroment in case multiple enviroments exist
# How to: enter the https authentication credentials under [https auth goes here] and adapt the URL structure in line 38
# manual opens with 'intcurl --help'

[ -z $1 ] && exit 
if [  $1 = "--help" ]
then echo "
intcurl [LOCALE] [STAGING ENV #] [URI] 

Required Options for intcurl

[LOCALE]
de Germany
at Austria
ch Switzerland
uk United Kingdom
nl Netherlands
fr France
be Belgium
fb french Belgium
dk Denmark
fi Finnland
se Sweden

[STAGING ENV #]
1 equals STG1
2 equals STG2
and so on..

[URI]
Just enter any URI as it would appear in the URL (See Example Below)

Example: intcurl uk 1 gardener - will test UK STG1 /gardener for a 301 Redirect
" 
else
curl -k -u [https auth goes here] --head https://"$1"-stg"$2".[server URL goes here]/"$3" | grep -A3 --color=always "301 Moved"
[ "$?" = 1 ] && echo "There is no 301 Redirect on the given ressource"
fi  
